#!/usr/bin/env bash
#
# To be executed by git (symbolically link as .git/hooks/pre-receive)
# For each commit, verify each hook configured for the repo
# @deprecated Please see ./bin/git-hook-runner for example of recommended approach
##

declare HOOK_SCRIPT='pre-receive.php'

# TODO Generalize this for upstream names ending in .git
declare GIT_DIR="$(pwd)"
declare REPO="$(basename $GIT_DIR)"

# Since this is typically run via symbolic link, figure out where we're really
# ...running.
declare BART_HOOKS="$(dirname $(readlink $0))"


# This processes the receive data and runs the hooks
. $BART_HOOKS/receive-hook
